name: Rust CI

on:
  workflow_dispatch:

jobs:
  build_linux:
    name: Build Linux ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            toolchain: stable
          - target: x86_64-unknown-linux-musl
            toolchain: stable
          - target: aarch64-unknown-linux-gnu
            toolchain: stable
          - target: aarch64-unknown-linux-musl
            toolchain: stable

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential pkg-config libssl-dev musl-tools \
            zip rpm curl xz-utils

      - name: Install musl-cross toolchain for aarch64
        if: matrix.target == 'aarch64-unknown-linux-musl'
        run: |
          curl -LO https://musl.cc/aarch64-linux-musl-cross.tgz
          tar -xzf aarch64-linux-musl-cross.tgz
          echo "$PWD/aarch64-linux-musl-cross/bin" >> $GITHUB_PATH

      - name: Install Rust and target
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: ${{ matrix.target }}

      - name: Install cargo-deb for .deb packaging
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: cargo install cargo-deb

      - name: Build binary
        env:
          OPENSSL_STATIC: "true"
        run: |
          if [[ "${{ matrix.target }}" == *"musl" ]]; then
            export RUSTFLAGS="-C target-feature=-crt-static"
            export CC_aarch64_unknown_linux_musl=aarch64-linux-musl-gcc
          fi
          cargo build --release --target=${{ matrix.target }}

      - name: Read crate metadata
        id: metadata
        run: |
          name=$(grep '^name =' Cargo.toml | head -n1 | sed 's/.*= \"\(.*\)\"/\1/')
          version=$(grep '^version =' Cargo.toml | head -n1 | sed 's/.*= \"\(.*\)\"/\1/')
          echo "name=$name" >> "$GITHUB_OUTPUT"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Package binary archives
        run: |
          ARTIFACT_DIR="target/${{ matrix.target }}/release"
          BINARY_NAME="${{ steps.metadata.outputs.name }}"
          tar czf "${ARTIFACT_DIR}/${BINARY_NAME}-${{ matrix.target }}.tar.gz" -C "${ARTIFACT_DIR}" "${BINARY_NAME}"
          zip -j "${ARTIFACT_DIR}/${BINARY_NAME}-${{ matrix.target }}.zip" "${ARTIFACT_DIR}/${BINARY_NAME}"

      - name: Package .deb
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: cargo deb --target=${{ matrix.target }} --no-build

      - name: Package .rpm
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          sudo apt-get install -y rpm-build
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          cargo package --no-verify --allow-dirty
          cp target/package/${{ steps.metadata.outputs.name }}-${{ steps.metadata.outputs.version }}.tar.gz ~/rpmbuild/SOURCES/
          rpmbuild -bb build/twig.spec

      - name: Upload Linux Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.target }}/release/*.tar.gz
            target/${{ matrix.target }}/release/*.zip
            target/debian/*.deb
            ~/rpmbuild/RPMS/**/*.rpm

  build_arch:
    name: Build Arch Linux pkg.tar.zst
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build .pkg.tar.zst using Docker
        run: |
          docker run --rm -v "$(pwd)":/repo archlinux:base-devel /bin/bash -c "
            set -euxo pipefail
            useradd -m builder
            echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
            pacman -Syu --noconfirm
            pacman -S --noconfirm rustup base-devel git sudo
            chown -R builder:builder /repo
            su builder -c '
              set -euxo pipefail
              cd /repo
              rustup default stable
              export CARGO_HOME=\$HOME/.cargo
              export RUSTUP_HOME=\$HOME/.rustup
              export PATH=\$CARGO_HOME/bin:\$PATH
              cd build
              makepkg -s --noconfirm
            '
          "

  build_macos:
    name: Build macOS ${{ matrix.target }}
    needs: [build_linux, build_arch]
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            toolchain: stable
          - target: aarch64-apple-darwin
            toolchain: stable

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust and target
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: ${{ matrix.target }}

      - name: Build binary
        run: cargo build --release --target=${{ matrix.target }}

      - name: Read crate metadata
        id: metadata
        run: |
          name=$(grep '^name =' Cargo.toml | head -n1 | sed 's/.*= \"\(.*\)\"/\1/')
          echo "name=$name" >> "$GITHUB_OUTPUT"

      - name: Package artifacts
        run: |
          ARTIFACT_DIR="target/${{ matrix.target }}/release"
          BINARY_NAME="${{ steps.metadata.outputs.name }}"
          tar czf "${ARTIFACT_DIR}/${BINARY_NAME}-${{ matrix.target }}.tar.gz" -C "${ARTIFACT_DIR}" "${BINARY_NAME}"
          zip -j "${ARTIFACT_DIR}/${BINARY_NAME}-${{ matrix.target }}.zip" "${ARTIFACT_DIR}/${BINARY_NAME}"

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.target }}/release/*.tar.gz
            target/${{ matrix.target }}/release/*.zip