name: Rust CI

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            toolchain: stable
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            toolchain: stable
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            toolchain: stable
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            toolchain: stable
          - os: macos-latest
            target: x86_64-apple-darwin
            toolchain: stable
          - os: macos-latest
            target: aarch64-apple-darwin
            toolchain: stable

    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies (Ubuntu only)
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential pkg-config libssl-dev musl-tools \
            gcc-aarch64-linux-gnu curl

      - name: Install Rust and target
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: ${{ matrix.target }}

      - name: Build binary
        # aarch64-musl 目标设置特定的 C 编译标志
        env:
          # CFLAGS_<target> 是被 cargo/cc crate 识别的标准方式
          # -D_FORTIFY_SOURCE=0 禁用了和 musl 不兼容的 glibc 安全特性，从而解决 __*_chk 链接错误
          CFLAGS_aarch64_unknown_linux_musl: "-D_FORTIFY_SOURCE=0"
          # 确保 openssl crate 知道我们想要一个静态库
          OPENSSL_STATIC: "true"
        run: |
          # Use vendored OpenSSL for all musl targets AND for aarch64-gnu cross-compilation
          if [[ "${{ matrix.target }}" == *"-musl" || "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]]; then
            cargo build --release --target=${{ matrix.target }} --no-default-features --features musl-vendored
          else
            # For native builds (x86_64-gnu) and macOS, build as normal
            cargo build --release --target=${{ matrix.target }}
          fi

      - name: Read crate metadata
        id: metadata
        run: |
          name=$(grep '^name =' Cargo.toml | head -n1 | sed 's/.*= "\(.*\)"/\1/')
          version=$(grep '^version =' Cargo.toml | head -n1 | sed 's/.*= "\(.*\)"/\1/')
          echo "name=$name" >> "$GITHUB_OUTPUT"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Package binary
        run: |
          cd target/${{ matrix.target }}/release
          tar czf "${{ steps.metadata.outputs.name }}-${{ matrix.target }}.tar.gz" ${{ steps.metadata.outputs.name }}

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.metadata.outputs.version }}
          name: v${{ steps.metadata.outputs.version }}
          files: target/${{ matrix.target }}/release/${{ steps.metadata.outputs.name }}-${{ matrix.target }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
